"use client";

import { useEffect, useRef, ReactNode } from "react";
import { useFormContext, useWatch } from "react-hook-form";
import { generateSlug } from "@/lib/utils";
import { FormField, FormItem, FormLabel, FormControl, FormMessage, FormDescription } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { X } from "lucide-react";

export function SlugFormField({ nameFieldName, label }: { nameFieldName: string; label?: ReactNode }) {
  const { control, setValue, formState: { isSubmitting } } = useFormContext();
  const watchedName = useWatch({ control, name: nameFieldName });
  const watchedSlug = useWatch({ control, name: "slug" });
  const lastAutoGeneratedSlug = useRef("");

  const isFirstRender = useRef(true);

  useEffect(() => {
    // On mount, if we have an existing slug (Edit Mode), 
    // we treat it as the last "auto-generated" one so that 
    // changing the name will immediately trigger an update.
    if (isFirstRender.current) {
      lastAutoGeneratedSlug.current = watchedSlug || "";
      isFirstRender.current = false;
      return;
    }

    const newSlug = generateSlug(watchedName || "");

    // Define if we should auto-update:
    // 1. Slug is empty (user cleared it)
    // 2. Slug currently matches our last recorded "auto" slug (user hasn't manually diverged)
    const shouldUpdate = !watchedSlug || watchedSlug === lastAutoGeneratedSlug.current;

    if (shouldUpdate && watchedSlug !== newSlug) {
      setValue("slug", newSlug, { shouldValidate: true });
      lastAutoGeneratedSlug.current = newSlug;
    }
  }, [watchedName, watchedSlug, setValue]);


  return (
    <FormField
      control={control}
      name="slug"
      render={({ field }) => (
        <FormItem>
          <FormLabel>{label || "Slug"}</FormLabel>
          <div className="relative group/field">
            <FormControl>
              <Input
                placeholder="URL-friendly slug"
                {...field}
                className="pr-8"
                disabled={isSubmitting}
              />
            </FormControl>
            {field.value && !isSubmitting && (
              <button
                type="button"
                onClick={() => setValue("slug", "")}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground p-0.5 rounded-md hover:bg-muted opacity-0 group-hover/field:opacity-100 transition-opacity"
              >
                <X className="h-4 w-4" />
              </button>
            )}
          </div>
          <FormDescription>
            This is the unique URL-friendly version of the name. It's automatically generated.
          </FormDescription>
          <FormMessage />
        </FormItem>
      )}
    />
  );
}
